COMPOSITIONS_BASIS: mole

FILLING_CONDITIONS:
  TEMPERATURE: 288.15  # K
  PRESSURE: 5201325  # Pa

BASE_COMPOSITIONS_LOWER_LIMITS:  # mol/mol
  CO2: 0.99953

IMPURITIES_UPPER_LIMITS:  # mol/mol
  WATER: 50.0e-06 
  OXYGEN: 60.0e-06
  ETHANE: 100.0e-06  # assuming THC is ethane
  CO: 10.0e-06
  NITROGEN: 250.0e-06

FLUID_PROPERTY: VIS  # Density

DOE:
  n_grid_temperature: 10
  n_grid_pressure: 10
  temperature_range: [310.15, 323.15]  # K
  pressure_range: [51325, 2101325]  # Pa