NITROGEN:
  N_GRID_TEMPERATURE: 500
  N_GRID_PRESSURE: 500
  TMIN: 278.15
  TMAX: 323.15
  PMIN: 200.0
  PMAX: 20101325.0
# HYDROGEN:
#   N_GRID_TEMPERATURE: 500
#   N_GRID_PRESSURE: 500
#   TMIN: 278.15
#   TMAX: 323.15
#   PMIN: 200.0
#   PMAX: 20101325.0
# METHANE:
#   N_GRID_TEMPERATURE: 500
#   N_GRID_PRESSURE: 500
#   TMIN: 278.15
#   TMAX: 323.15
#   PMIN: 200.0
#   PMAX: 20101325.0
# CO2:
#   N_GRID_TEMPERATURE: 500
#   N_GRID_PRESSURE: 500
#   TMIN: 283.15
#   TMAX: 323.15
#   PMIN: 200.0
#   PMAX: 3101325.0